#!/usr/bin/env ts-node

/**
 * generate-docs - Documentation Generator for FHEVM Examples
 * 
 * Generates:
 * 1. Markdown documentation for each example (from JSDoc + catalog + Code)
 * 2. SUMMARY.md for GitBook
 */

import { fileURLToPath } from 'url';
import * as fs from 'fs';
import * as path from 'path';

// Fix for __dirname in ESM
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load catalog
const CATALOG_PATH = path.join(__dirname, '..', 'example-catalog.json');
let EXAMPLES_MAP: Record<string, any> = {};

try {
    const catalogContent = fs.readFileSync(CATALOG_PATH, 'utf-8');
    EXAMPLES_MAP = JSON.parse(catalogContent);
} catch (e) {
    console.error('Failed to load example catalog:', e);
    process.exit(1);
}

const OUTPUT_DOCS_DIR = path.join(__dirname, '..', 'docs');
const EXAMPLES_DOCS_DIR = path.join(OUTPUT_DOCS_DIR, 'examples');
const ROOT_DIR = path.resolve(__dirname, '..');

// Helper to ensure directory exists
function ensureDir(dir: string) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

// Helper to read file content safely
function readFileContent(relativePath: string): string {
    const fullPath = path.join(ROOT_DIR, relativePath);
    if (fs.existsSync(fullPath)) {
        return fs.readFileSync(fullPath, 'utf-8');
    }
    return '// File not found';
}

// Get level badge
function getLevelBadge(tags: string[]): string {
    if (tags.includes('beginner')) return '🟢 Beginner';
    if (tags.includes('advanced')) return '🔴 Advanced';
    return '🟡 Intermediate';
}

// Generate Key Concepts section
function generateKeyConcepts(concepts: string[] | undefined): string {
    if (!concepts || concepts.length === 0) return '';

    const items = concepts.map(c => `- \`${c}\``).join('\n');
    return `
## 🧠 Key FHE Concepts Used

${items}
`;
}

// Generate single example documentation
function generateExampleDoc(key: string, config: any) {
    const docPath = path.join(EXAMPLES_DOCS_DIR, config.category, `${key}.md`);
    ensureDir(path.dirname(docPath));

    const contractContent = readFileContent(config.contract);
    const testContent = readFileContent(config.test);
    const levelBadge = getLevelBadge(config.tags);
    const keyConcepts = generateKeyConcepts(config.keyConcepts);
    const extraDoc = config.extraDoc || '';

    const content = `---
id: ${key}
title: ${config.title}
category: ${config.category}
tags: [${config.tags.join(', ')}]
description: ${config.description}
---

# ${config.title}

> ${config.description}

## Overview

This example demonstrates how to implement **${config.title}** using FHEVM.

| Property | Value |
|----------|-------|
| **Level** | ${levelBadge} |
| **Category** | ${config.category} |
| **Key** | \`${key}\` |
${extraDoc}${keyConcepts}
## 📝 Contract Implementation

\`contracts/${path.basename(config.contract)}\`

\`\`\`solidity
${contractContent}
\`\`\`

## 🧪 Test Suite

\`test/${path.basename(config.test)}\`

\`\`\`typescript
${testContent}
\`\`\`

## 🚀 Quick Start

Generate this example locally:

\`\`\`bash
# Using npx (no install)
npx jobjab-fhevm-examples ${key} ./my-${key}

# Or with the CLI
npm run create ${key} ./my-${key}
\`\`\`

Then build and test:

\`\`\`bash
cd ./my-${key}
npm install
npm run compile
npm run test
\`\`\`

---
*Generated by FHEVM Example Hub*
`;

    fs.writeFileSync(docPath, content);
    console.log(`✓ Generated doc for ${key}`);
}

// Generate SUMMARY.md for GitBook
function generateSummary() {
    const categories: Record<string, string[]> = {};

    // Group by category
    Object.entries(EXAMPLES_MAP).forEach(([key, config]: [string, any]) => {
        if (!categories[config.category]) {
            categories[config.category] = [];
        }
        categories[config.category].push(key);
    });

    // Category display names
    const categoryNames: Record<string, string> = {
        basic: '🐣 Basic',
        encryption: '🔐 Encryption',
        decryption: '🔓 Decryption',
        operations: '🧮 Operations',
        concepts: '🧠 Concepts',
        applications: '🚀 Applications',
        labs: '🧪 Security Labs',
        openzeppelin: '🏦 OpenZeppelin'
    };

    let summaryContent = `# FHEVM Example Hub Documentation

> 📚 Complete reference for all FHEVM examples

## Quick Links

- [Getting Started](../README.md)
- [Example Catalog](../example-catalog.json)

## Examples by Category

`;

    // Sort categories in logical order
    const categoryOrder = ['basic', 'encryption', 'decryption', 'operations', 'concepts', 'applications', 'labs', 'openzeppelin'];

    categoryOrder.forEach(category => {
        if (!categories[category]) return;

        const displayName = categoryNames[category] || category.charAt(0).toUpperCase() + category.slice(1);
        summaryContent += `### ${displayName}\n\n`;
        summaryContent += `| Example | Description |\n`;
        summaryContent += `|---------|-------------|\n`;

        categories[category].forEach(key => {
            const config = EXAMPLES_MAP[key];
            summaryContent += `| [${config.title}](examples/${config.category}/${key}.md) | ${config.description} |\n`;
        });

        summaryContent += `\n`;
    });

    summaryContent += `---
*Auto-generated by \`npm run docs\`*
`;

    fs.writeFileSync(path.join(OUTPUT_DOCS_DIR, 'SUMMARY.md'), summaryContent);
    console.log('✓ Generated SUMMARY.md');
}

function main() {
    console.log('📚 Generating Documentation...');
    ensureDir(EXAMPLES_DOCS_DIR);

    Object.entries(EXAMPLES_MAP).forEach(([key, config]) => {
        generateExampleDoc(key, config);
    });

    generateSummary();
    console.log('✅ Documentation generation complete!');
}

main();
