#!/usr/bin/env ts-node

/**
 * generate-docs - Documentation Generator for FHEVM Examples
 * 
 * Generates:
 * 1. Markdown documentation for each example (from JSDoc + catalog + Code)
 * 2. SUMMARY.md for GitBook
 */

import * as fs from 'fs';
import * as path from 'path';

// Load catalog
const CATALOG_PATH = path.join(__dirname, '..', 'example-catalog.json');
let EXAMPLES_MAP: Record<string, any> = {};

try {
    const catalogContent = fs.readFileSync(CATALOG_PATH, 'utf-8');
    EXAMPLES_MAP = JSON.parse(catalogContent);
} catch (e) {
    console.error('Failed to load example catalog:', e);
    process.exit(1);
}

const OUTPUT_DOCS_DIR = path.join(__dirname, '..', 'docs');
const EXAMPLES_DOCS_DIR = path.join(OUTPUT_DOCS_DIR, 'examples');
const ROOT_DIR = path.resolve(__dirname, '..');

// Helper to ensure directory exists
function ensureDir(dir: string) {
    if (!fs.existsSync(dir)) {
        fs.mkdirSync(dir, { recursive: true });
    }
}

// Helper to read file content safely
function readFileContent(relativePath: string): string {
    const fullPath = path.join(ROOT_DIR, relativePath);
    if (fs.existsSync(fullPath)) {
        return fs.readFileSync(fullPath, 'utf-8');
    }
    return '// File not found';
}

// Generate single example documentation
function generateExampleDoc(key: string, config: any) {
    const docPath = path.join(EXAMPLES_DOCS_DIR, config.category, `${key}.md`);
    ensureDir(path.dirname(docPath));

    const contractContent = readFileContent(config.contract);
    const testContent = readFileContent(config.test);

    const content = `---
id: ${key}
title: ${config.title}
category: ${config.category}
tags: [${config.tags.join(', ')}]
description: ${config.description}
---

# ${config.title}

> ${config.description}

## Overview

This example demonstrates how to implement **${config.title}** using FHEVM.

- **Level:** ${config.tags.includes('beginner') ? '🟢 Beginner' : config.tags.includes('advanced') ? '🔴 Advanced' : '🟡 Intermediate'}
- **Category:** ${config.category}
${config.extraDoc || ''}
## 📝 Contract Implementation

\`contracts/${path.basename(config.contract)}\`

\`\`\`solidity
${contractContent}
\`\`\`

## 🧪 Test Suite

\`test/${path.basename(config.test)}\`

\`\`\`typescript
${testContent}
\`\`\`

## Usage

To generate this example locally:

\`\`\`bash
npx run create ${key} ./my-${key}
\`\`\`

Then run tests:

\`\`\`bash
cd ./my-${key}
npm install
npm run test
\`\`\`

---
Generated by FHEVM Example Hub
`;

    fs.writeFileSync(docPath, content);
    console.log(`✓ Generated doc for ${key}`);
}

// Generate SUMMARY.md for GitBook
function generateSummary() {
    const categories: Record<string, string[]> = {};

    // Group by category
    Object.entries(EXAMPLES_MAP).forEach(([key, config]: [string, any]) => {
        if (!categories[config.category]) {
            categories[config.category] = [];
        }
        categories[config.category].push(key);
    });

    let summaryContent = '# Summary\n\n';

    Object.keys(categories).sort().forEach(category => {
        const categoryTitle = category.charAt(0).toUpperCase() + category.slice(1);
        summaryContent += `* [${categoryTitle}](chapters/${category}.md)\n`;
        
        categories[category].forEach(key => {
            const config = EXAMPLES_MAP[key];
            summaryContent += `  * [${config.title}](examples/${config.category}/${key}.md)\n`;
        });
    });

    fs.writeFileSync(path.join(OUTPUT_DOCS_DIR, 'SUMMARY.md'), summaryContent);
    console.log('✓ Generated SUMMARY.md');
}

function main() {
    console.log('📚 Generating Documentation...');
    ensureDir(EXAMPLES_DOCS_DIR);

    Object.entries(EXAMPLES_MAP).forEach(([key, config]) => {
        generateExampleDoc(key, config);
    });

    generateSummary();
    console.log('✅ Documentation generation complete!');
}

main();
