
import { glob } from 'glob';
import fs from 'fs-extra';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.join(__dirname, '..');
const OUTPUT_FILE = path.join(ROOT_DIR, 'app', 'src', 'data', 'repo_context.ts');

const ZAMA_KNOWLEDGE_BASE = `
# Zama FHEVM Knowledge Base

## Core Concepts
- **Fully Homomorphic Encryption (FHE):** Allows computation on encrypted data without decrypting it.
- **TFHE-rs:** Zama's Rust implementation of TFHE. Fast and secure.
- **FHEVM:** An extension of the EVM that adds FHE capabilities (precompiled contracts).
- **Privacy:** Users encrypt inputs. The network computes on them. The result is encrypted. Only the user with the key (or a threshold of authorities) can decrypt.

## FHE Examples & Patterns
- **Confidential ERC20:** Standard patterns include encrypted balances (euint64), encrypted transfers, and using \`FHE.allow\` to let users view their own balance.
- **Blind Auctions:** Bids are encrypted. The contract compares them using \`FHE.lt\` or \`FHE.select\`. The winner is determined without revealing losing bids.
- **Voting:** Votes are encrypted (e.g., ebool or euint8). The tally is computed homomorphically. Only the final result is decrypted.
- **Identity:** Encrypted attributes (age, credit score) can be checked against thresholds without revealing the exact value.

## Solidity API (FHE Library)
- \`FHE.asEuintXX(value)\`: Trivial encryption (for public constants).
- \`FHE.add(a, b)\`, \`FHE.sub\`, \`FHE.mul\`, \`FHE.div\`: Arithmetic.
- \`FHE.eq(a, b)\`, \`FHE.ne\`, \`FHE.gt\`, \`FHE.ge\`, \`FHE.lt\`, \`FHE.le\`: Comparisons.
- \`FHE.select(condition, ifTrue, ifFalse)\`: Encrypted multiplexer (if-else).
- \`FHE.req(condition)\`: Optimistic requirement (deprecated/discouraged in favor of branching).
- \`FHE.allow(ciphertext, address)\`: Re-encryption for viewing.
- \`FHE.seal(contractAddress, ciphertext)\`: Binds ciphertext to a contract.

## Project Structure
- This repository contains example use cases.
- Use \`npx create-fhevm-example [key] [path]\` to instantiate an example.
`;

async function generateContext() {
    console.log('Generating AI Context...');

    // 1. Read Examples
    const files = await glob('examples/**/*.{sol,ts,js,md}', {
        cwd: ROOT_DIR,
        ignore: ['**/node_modules/**', '**/artifacts/**', '**/cache/**', '**/typechain-types/**']
    });

    // 2. Read README
    const readmePath = path.join(ROOT_DIR, 'README.md');
    const readmeContent = await fs.readFile(readmePath, 'utf-8').catch(() => '');

    let contextContent = `${ZAMA_KNOWLEDGE_BASE}\n\n# Project README\n${readmeContent}\n\n# Codebase Examples\n`;

    for (const file of files) {
        const filePath = path.join(ROOT_DIR, file);
        const content = await fs.readFile(filePath, 'utf-8');
        contextContent += `\n## File: ${file}\n\`\`\`\n${content}\n\`\`\`\n`;
    }

    // 3. Write to file
    const fileContent = `// This file is auto-generated by scripts/generate-ai-context.ts
// Do not edit manually.

export const REPO_CONTEXT = ${JSON.stringify(contextContent)};
`;

    await fs.ensureDir(path.dirname(OUTPUT_FILE));
    await fs.writeFile(OUTPUT_FILE, fileContent);
    console.log(`Context written to ${OUTPUT_FILE} (${contextContent.length} chars)`);
}

generateContext().catch(console.error);
